openapi: 3.0.0
info:
  title: outbreaknewstoday
  version: '1.0'
  description: A REST API for querying a database of outbreak reports scraped from Outbreak News Today
  contact:
    name: Amir Mosaddad
    email: mosaddad.amir@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  /articles:
    parameters: []
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
        '204':
          description: No Content
        '400':
          description: Bad Request
      operationId: 'get-articles-location,keyTerms,date'
      parameters:
        - $ref: '#/components/parameters/Location'
        - $ref: '#/components/parameters/Keyterm'
        - $ref: '#/components/parameters/Start_Date'
        - $ref: '#/components/parameters/End_Date'
      description: Retrieve list of articles based on the users' query params.
components:
  schemas:
    Location:
      title: Location
      type: object
      properties:
        country:
          type: string
          description: name of the country
        location:
          type: string
          description: any other information about the location
      x-examples:
        example-1:
          country: Australia
          location: NSW
      description: Basic location model
    Disease:
      title: Disease
      type: string
      x-examples:
        example-1: string
      description: Disease model is a string numeration
    Syndrome:
      title: Syndrome
      type: string
      description: Sydndrome model is a string numeration
    Report:
      title: Report
      type: object
      properties:
        Diseases:
          type: array
          items:
            $ref: '#/components/schemas/Disease'
        Syndromes:
          type: array
          items:
            $ref: '#/components/schemas/Syndrome'
        Event_date:
          $ref: '#/components/schemas/Date'
        Locations:
          type: array
          items:
            $ref: '#/components/schemas/Location'
      description: An object containing information about a case mentioned in an article.
    Date_Exact:
      type: string
      title: Date_Exact
      pattern: '^(\d{4})-(\d\d|xx)-(\d\d|xx) (\d\d|xx):(\d\d|xx):(\d\d|xx)$'
      x-examples:
        example-1: '2018-xx-xx xx:xx:xx'
        example-2: '2018-11-01 xx:xx:xx'
        example-3: '2018-11-xx 17:00:xx'
      description: |-
        yyyy-mm-dd hh:mm:ss format. Year is mandatory, every other segment is optional. Use 'x'
        character if missing. 
    Date_Range:
      type: string
      title: Date_Range
      pattern: '^(\d{4})-(\d\d|xx)-(\d\d|xx) (\d\d|xx):(\d\d|xx):(\d\d|xx) to (\d{4})-(\d\d|xx)-(\d\d|xx) (\d\d|xx):(\d\d|xx):(\d\d|xx)$'
      x-examples:
        example-1: '2018-xx-xx xx:xx:xx to 2019-xx-xx xx:xx:xx'
        example-2: '2018-11-01 17:xx:xx to 2018-12-xx xx:xx:xx'
      description: first date must be a date before the second date
    Date:
      title: Date
      oneOf:
        - $ref: '#/components/schemas/Date_Exact'
        - $ref: '#/components/schemas/Date_Range'
      description: Date references
    Article:
      title: Article
      type: object
      description: |-
        API should also transmit article data using this json schema - so that other
        groups know what to expect from your API.
      properties:
        url:
          type: string
          format: uri
        date_of_publication:
          $ref: '#/components/schemas/Date_Exact'
        headline:
          type: string
        main_text:
          type: string
        reports:
          type: array
          items:
            $ref: '#/components/schemas/Report'
  securitySchemes: {}
  responses:
    Report_response:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              articles:
                type: array
                items:
                  $ref: '#/components/schemas/Article'
        application/xml:
          schema:
            type: object
            properties:
              type:
                type: string
              message:
                type: string
  parameters:
    Location:
      name: Location
      in: query
      required: true
      schema:
        type: string
        example: '"Australia,NSW"'
      description: country name is essential
    Keyterm:
      name: Keyterm
      in: query
      required: true
      schema:
        type: string
        example: '"Anthrax,Zika"'
      description: 'Disease,Syndrome...'
    Start_Date:
      name: Start_Date
      in: query
      schema:
        type: string
        example: '“2015-10-01T08:45:10”'
      required: true
    End_Date:
      name: End_Date
      in: query
      required: true
      schema:
        type: string
        example: '“2015-11-01T19:37:12”'
tags:
  - name: Outbreak News Today
